- src/Utils/DateTime.php
Changed signature of DateTime::createFromFormat in PHP7 makes a lot of Nette tests fail.
We may
A) ignore it for now
B) workaround it
C) remove the method entirely
> Workaround (hopefully temporary) for changed signature of DateTime::createFromFormat in PHP7

- src/Utils/Random.php
- tests/Utils/Random.generate().no-mcrypt.phpt
- tests/Utils/Random.generate().no-openssl.phpt
- tests/php-win.ini
Not sure whether the generateBytes() refactoring is worth it. It's still a bit ugly.
> Random: use random_bytes() on PHP 7

- src/Utils/DateTime.php
This reverts commit 85c4cd90029a152c4d6b61a256edb3ca7cd45ae4. Confirmed to work with the latest PHP 7 snapshot.
> Revert "DateTime: workaround for changed signature of createFromFormat() in PHP 7 [closes #58]"

- src/Utils/Json.php
- tests/Utils/Json.decode().phpt
Json: accept whitespace-surrounded `"null"` for `decode()` as it is a valid JSON text. As the standard says: "Insignificant whitespace is allowed before or after any token." Therefore, `" null   "` and others are legal, although `Json` throws an exception for such input.
> Json: accept whitespace-surrounded "null" for decode()

- src/Utils/Strings.php
**BC break**: No
**Doc**: not-needed
**Motivation**: Sometimes I need trim also characters like  `ZERO WIDTH NO-BREAK SPACE` (yes, sadly there is an API that uses it in JSON response). If I want to use `Strings::trim` it forces me to *copy-paste* code for extending the character-mask.
```php
$zeroWithNoBreakSpace =  "\xEF\xBB\xBF";
Strings::trim($rawResponse, " \t\n\r\0\x0B\xC2\xA0" . $zeroWithNoBreakSpace);
```
vs. 
```php
$zeroWithNoBreakSpace =  "\xEF\xBB\xBF";
Strings::trim($rawResponse, Strings::TRIM_CHARACTER_MASK . $zeroWithNoBreakSpace);
```
***
**Note**: *I'm not really sure about naming for that constant. I will be happy if you suggest some better name.*
> Trim Character Mask extracted into CONST

- src/Utils/Callback.php
- src/Utils/Image.php
- src/Utils/Json.php
- src/Utils/Strings.php
Depends on #79 (for composer & Travis PHP version bump).
> PHP 5.6: Use variadics and argument unpacking

- tests/Utils/Callback.invokeSafe.phpt
1. `Callback::invokeSafe`  - `trim([])` throws `TypeError` in strict mode so I picked another function.
2.  `Image::rotate()` test does't work in strict mode because `imagecolorallocatealpha` returns `false`. The image resource is changed somehow by other tests. It's safer to run all tests independently.
> Fixed tests in PHP7 strict mode

- src/Utils/Strings.php
It's expensive to create `Transliterator` instance everytime.
> Strings::toAscii() optimization

- src/Utils/Html.php
- tests/Utils/Html.children.phpt
https://twitter.com/jakubvrana/status/733655999618404352
> Rename Html:add() to Html:addHtml()

- src/Utils/FileSystem.php
Directory can be created by concurrent process. Similar solution by Symfony in this issue https://github.com/symfony/symfony/pull/11726
> FileSystem: fix mkdir race condition

- src/Iterators/CachingIterator.php
- src/Utils/ArrayHash.php
- src/Utils/ArrayList.php
- src/Utils/Arrays.php
- src/Utils/Callback.php
- src/Utils/DateTime.php
- src/Utils/FileSystem.php
- src/Utils/Html.php
- src/Utils/IHtmlString.php
- src/Utils/ITranslator.php
- src/Utils/Image.php
- src/Utils/Json.php
- src/Utils/ObjectMixin.php
- src/Utils/Paginator.php
- src/Utils/Random.php
- src/Utils/Reflection.php
- src/Utils/SmartObject.php
- src/Utils/Strings.php
- src/Utils/Validators.php
- tests/Utils/Random.generate().phpt
> Version 3.0

- src/Utils/Reflection.php
- tests/Utils/Reflection.getParameterDefaultValue.phpt
- bug fix? yes
- BC break? no
- doc PR: not needed
`Reflection::getParameterDefaultValue()` does not properly resolve global constants used as default parameter values in namespaced classes.
> Reflection::getParameterDefaultValue() fixed constants parsing in namespaced scope

- tests/Utils/Json.decode().phpt
- bug fix? no, ref. #83
- BC break? no
PR is for v2.4 branch.
This is only headless test fix. I didn't think about fixing Json class.
> tests: fix for JSON-C extension on Debian/Ubuntu

- src/Utils/Arrays.php
- src/Utils/DateTime.php
- src/Utils/Strings.php
- tests/Utils/Arrays.searchKey().phpt
- tests/Utils/DateTime.createFromFormat.phpt
- tests/Utils/Strings.after().phpt
- tests/Utils/Strings.before().phpt
- tests/Utils/Strings.indexOf().phpt
- bug fix? no  
- BC break? yes
Returning FALSE on error is old way, not compatible with PHP 7.1 return type hints.
> Returns NULL instead of FALSE on error

- src/Utils/FileSystem.php
- bug fix? yes
- BC break? no (fixing unintended Nette 2.x BC break)
Code of function expects `$mode` to be `NULL`. If that happens it does not `chmod` it.
> Filesystem::write() accept NULL in $mode parameter

- composer.json
- src/Utils/Strings.php
- tests/Utils/Strings.compare().phpt
- tests/Utils/Strings.normalize().phpt
- tests/php-win.ini
- bug fix? no   
- new feature? yes
- BC break? yes
implementation of #149 
Before merge:
> Strings: normalize strings into UTF-8 NFC

- src/Utils/Reflection.php
- tests/Utils/Reflection.getParameterDefaultValue.php71.phpt
- tests/Utils/fixtures.reflection/defaultValue.71.php
- bug fix? yes
- BC breakno
- fixes #154
> Reflection::getParameterDefaultValue: fix constant visibility handling

- src/Utils/Random.php
- tests/Utils/Random.generate().phpt
- bug fix? no
- BC break? no
Fix a typo in an exception message thrown when character list contains less than two chars.
> Fix typo in exception message

- src/Utils/Html.php
- tests/Utils/Html.basic.phpt
- bug fix? no 
- new feature? yes
**Description**
- Added method removeAttributes for removing multiple attributes
- Why: for example when converting html element to the Amp html element, sometimes is necessary to remove multiple (by Amp disabled) attributes like frameborder, allowfullscreen or scrolling
- There is already a method for setting multiple attributes but non for removing multiple attributes so it means to create loops in order to remove them
> Added removeAttributes method - removing multiple attributes

- src/Utils/FileSystem.php
- bug fix? yes
- BC break? no
When trying to rename file/directory itself in order to change only case of filename (eg. `test.php` to `Test.php`), the process fails as the method first [deletes](https://github.com/nette/utils/blob/master/src/Utils/FileSystem.php#L110) the desired file(name) prior to renaming it .. thus it deletes the original file/dir that was about to be renamed.
This change prevents that case.
> FileSystem::rename() fix renaming file/directory if only case changes

- src/Utils/Image.php
- tests/Utils/Image.save.phpt
Fixes problem with calling 'pathinfo()' with null filename.
- bug fix? yes
- BC break? no
> Image: throw exception when $file and $type is null

- src/Utils/Validators.php
- tests/Utils/Validators.is().phpt
- bug fix? no
- new feature? yes
- BC break? no
- doc PR: n/a
For whatever reason numeric strings with explicitly positive values (i.e. `+1` instead of just `1`) have not been considered as valid numerics even though they are perfectly valid (in the sense that even forcibly changing their type to the respective numeric type works as expected).
This PR fixes that issue, adding consistency with PHP and the way numbers can be written to the Validator class.
I have marked this as "not bc breaking" because (1) this use case has not been covered by tests, so it doesn't change any and (2) nobody should accept `'-1'` as a valid value and expect `'+1'` to fail.
Please merge this with squash; I accidentally made one too many commits.
> Adds the plus character as a valid option in numeric strings

- src/Utils/Strings.php
- new feature
- BC break? no
Strings performance improvements when working with string length.
> Strings: Optimalize strlen() for better performance.

- src/Utils/Image.php
- tests/Utils/Image.toString.phpt
- new feature
- BC break? no
Changed:
- `__sleep` must return array. Documentation: https://www.php.net/manual/en/language.oop5.magic.php#object.sleep
- `__toString` missing return statement.
> Add __toString() return statement + __sleep() return type.

- src/Utils/Arrays.php
- new feature
- BC break? no
Changed:
- `associate`: Avoid callables in loop conditionals for better performance.
- `associate`: Condition `$parts === ['->']` execution costs less than the previous one
- `normalize`: Duplicated method calls should be moved to a local variable for better performance.
> Arrays: Better performance

- src/Utils/FileSystem.php
- new feature
- BC break? yes
`copy`: The mode is not binary-safe ('b' is missing).
> FileSystem: copy: Add binary safe parameter

- src/Utils/Strings.php
- tests/Utils/Strings.toAscii().phpt
- tests/Utils/Strings.webalize().phpt
- bug fix
- BC break? no
Since `Strings::webalize()` can be called on user input it should be able to deal with anything or error in a predicable way. But when an malformed UTF-8 input is given currently it results in:
```
Nette\Utils\RegexpException was expected but got TypeError (strtr() expects parameter 1 to be string, null given)
```
(i guess this behaved differently before scrict types were added in [3.0.0](https://github.com/nette/utils/releases/tag/v3.0.0)).
Throwing an exception (the same exception as in other cases such as `Strings::replace()`) seems reasonable to me.
I am also not sure why the internal handling of PCRE is not used everywhere in calling `preg_*` is not used everywhere in the file, because there might be of course other problems too?
> Strings: throw exception on malformed UTF-8 in webalize() and toAscii()

- src/Utils/Strings.php
- bug fix
- BC break? yes
In case of `Strings::normalize("... \xbee m\xc3\xa1\xc5\xa1 ...");` normalizer throw error, because `\Normalizer::normalize` can return `false` in case of invalid string.
Now normalized string will be used only in case of valid return. In other cases keep original.
Thanks.
> Strings: Fix boolean return of Normalizer.

- src/Utils/Json.php
- bug fix
- BC break? no
Adds missing PHPDoc `@throws JsonException` in `JSON::encode` and `JSON::decode`.
> Json: missing @throws JsonException

- src/Utils/FileSystem.php
- new feature
- BC break? no
For production debug is better when current mode is displayed in exception message.
> FileSystem::write(): Exception should contain current mode for better debug

- src/Utils/Strings.php
- bug fix
- BC break? no
Constant ICONV_IMPL can contain quotes on some systems.
I could not find any official description why that is, same problem was reported here for example https://github.com/techdivision/import/pull/173
> Fix ICONV_IMPL constant

- src/Utils/Floats.php
- tests/Utils/Floats.areEqual().phpt
- tests/Utils/Floats.compare().phpt
- tests/Utils/Floats.isGreaterThan().phpt
- tests/Utils/Floats.isGreaterThanOrEqualTo().phpt
- tests/Utils/Floats.isInteger().phpt
- tests/Utils/Floats.isLessThan().phpt
- tests/Utils/Floats.isLessThanOrEqualTo().phpt
- tests/Utils/Floats.isZero().phpt
- new feature
- BC break? no
- doc PR: https://github.com/nette/docs/pull/848
---
Added support for comparing floats
The original class was created by @fabik.
I've added tests, and some fixes in the method `compare`.
> Added Nette\Utils\Floats helper

- src/Utils/Arrays.php
- src/Utils/Callback.php
- tests/Utils/Arrays.wrap().phpt
- tests/Utils/Callback.invokeAll.phpt
- new feature
- BC break? no
- doc PR: will
I'm using such conctruction quite often, maybe I'm not the only one.
> Arrays: added wrap() method

- src/Utils/Validators.php
- bug fix
- BC break? no
Value is always string + preg_match should be strict.
> Validators::isPhpIdentifier(): Value is always string.

- src/Utils/Validators.php
- tests/Utils/Validators.isNumeric().phpt
- bug fix
- BC break? no
The goal of this change is same behavior for float and string number.
```php
Validators::isNumeric(1.); // float number true
Validators::isNumeric('1.'); // string number false
```
```php
Validators::isNumeric(1.); // float number true
Validators::isNumeric('1.'); // string number true
```
And I wrote test for to keep back compatibility. How you can see in three commits.
> Validators: isNumeric support string number '1.'

- composer.json
- src/Utils/Strings.php
https://github.com/JetBrains/phpstorm-attributes#language
> Use Language RegExp attribute

- composer.json
- src/Utils/ArrayList.php
- src/Utils/Type.php
- src/Utils/Validators.php
- tests/Utils/Type.isValid.phpt
~~~php
$arrayList = ArrayList::form([['id'=>1],['id'=>2]]);
// $arrayList => [['id'=>1],['id'=>2]]
foreach($arrayList as &$item)
{
$item['id'] += 1;
}
unset($item);
// $arrayList => [['id'=>2],['id'=>3]]
~~~
> ArrayList support returning references 

- src/Utils/DateTime.php
- tests/Utils/DateTime.modifyClone.phpt
- bug fix 
- BC break? yes/no?
I have a problem with `Nette\Utils\DateTime`. I use `modifyClone` method:
```php
$date = new Nette\Utils\DateTime('now');
$date->modifyClone('xx'); // Invalid date string
```
And this cause the error:
` TypeError: Nette\Utils\DateTime::modifyClone(): Return value must be of type Nette\Utils\DateTime, bool returned`
because `DateTime::modify` returns `DateTime|false` and Warning:
`E_WARNING: DateTime::modify(): Failed to parse time string (xx) at position 0 (x): The timezone could not be found in the database`
We can solve it by that object will only cloned like that:
```php
public function modifyClone(string $modify = ''): static
{
$dolly = clone $this;
return $modify ? (@$dolly->modify($modify) ?: $dolly) : $dolly;
}
```
or we can throw an exception:
```php …
```
> DateTime: Fix type error - modifyClone

- src/Utils/DateTime.php
-  new feature?  no, only update
- BC break? no
- doc PR: nette/docs#???  not need
- keep right timezone
- compact syntax
- little bit faster, let's try
```php
function measure(callable $test): float
{
$start = microtime(true);
for ($i = 0; $i < 1000; ++$i) {
$test($i);
}
return microtime(true) - $start;
}
echo 'Datetime' . PHP_EOL;
echo measure(static function (int $i) {
return (new DateTime())->setTimestamp($i);
}) . PHP_EOL;
echo measure(static function (int $i) {
return (new DateTime('@' . $i))->setTimezone(new \DateTimeZone(date_default_timezone_get()));
}) . PHP_EOL;
echo 'DatetimeImmutable' . PHP_EOL;
echo measure(static function (int $i) {
return (new DateTimeImmutable())->setTimestamp($i);
}) . PHP_EOL;
echo measure(static function (int $i) {
return (new DateTimeImmutable('@' . …
```
> DateTime: build from timestamp use method setTimestamp()

- src/Utils/Strings.php
- tests/Utils/Strings.trim().phpt
- new feature
- BC break? yes - if someone relies on having ZWSP non-trimmed while using default parameter.
- doc PR: Not needed, function is covered and does not mention the default characters
Sneaky [Zero-Width Space char \u{200B}](https://www.fileformat.info/info/unicode/char/200b/index.htm) is currently untrimmed by `trim` function, while I'd expect it to do so.
Workaround:
1. Fork or extend the class and overwrite default param
2. Manually set updated charlist as second argument to every `trim()` call
> Strings improvement: trim ZWSP char
